// firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuvMdEr273V0jxQVbANTIIxFldHMdp6us',
    appId: '1:1094230363784:web:ea00f0a544b51dfc78593d',
    messagingSenderId: '1094230363784',
    projectId: 'parental-assistant',
    authDomain: 'parental-assistant.firebaseapp.com',
    storageBucket: 'parental-assistant.firebasestorage.app',
    measurementId: 'G-4PR1DT312S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQgWoJN4roMBwL_SsF1U9QBgBfJ_5-xUY',
    appId: '1:1094230363784:android:1d16fb2dcdf8c08078593d',
    messagingSenderId: '1094230363784',
    projectId: 'parental-assistant',
    storageBucket: 'parental-assistant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoeGmOgbTzAGdUxYH0dV2CAk2cizQyk_U',
    appId: '1:1094230363784:ios:cdd89396537ddbff78593d',
    messagingSenderId: '1094230363784',
    projectId: 'parental-assistant',
    storageBucket: 'parental-assistant.firebasestorage.app',
    iosBundleId: 'com.example.parentalAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoeGmOgbTzAGdUxYH0dV2CAk2cizQyk_U',
    appId: '1:1094230363784:ios:cdd89396537ddbff78593d',
    messagingSenderId: '1094230363784',
    projectId: 'parental-assistant',
    storageBucket: 'parental-assistant.firebasestorage.app',
    iosBundleId: 'com.example.parentalAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuvMdEr273V0jxQVbANTIIxFldHMdp6us',
    appId: '1:1094230363784:web:e891451863a986b078593d',
    messagingSenderId: '1094230363784',
    projectId: 'parental-assistant',
    authDomain: 'parental-assistant.firebaseapp.com',
    storageBucket: 'parental-assistant.firebasestorage.app',
    measurementId: 'G-1SGVSYWLL1',
  );
}
